### ISSUE TITLE
ESP32 Large File OTA fail 

### ISSUE THREAD

**Issue by mightChamp** [Schallie/ESP32-LilyGo-T-Call-SIM800-Smart-Plug#1]
Hello,

We are using your code for OTA, smaller file size as your example, works , but Our code size is about 998368 bytes, after 10-30% fail . Sometime at 90% OTA Fail.

OTA Fail Reason :
1) NO ERROR
2) FATAL Timeout

Please help us solve this problem.

Thank You

**Comment by SchalkVisser** [comment]
Hi

First I must give you a disclaimer: I coded this for a virtual Grade 11 Expo project (due to covid), and never actually ran the code to see if it works on an esp32. Did you use most of the code or only the OTA part? There are many better OTA sketches out there you can use such as described here: https://randomnerdtutorials.com/esp32-over-the-air-ota-programming/

In general for troubleshooting OTA(for Wi-Fi, I don't know how cellular OTA works): 
-Make sure Wi-Fi connection strong
-plug into USB serial at baud rate 115200 to see raw output from ESP32
-Isolate the esp32 from the rest of the circuit - I suspect interrupt pins may accidentally be triggered
-Give ESP32 a static IP through your Wi-Fi router
-Rewrite your code around the BasicOTA or OTAWebUpdater examples from https://github.com/espressif/arduino-esp32/tree/master/libraries/ArduinoOTA


Hope this helps

**Comment by mightChamp** [comment]
I have tested all ota everythings works fine expect through GSM, may be network issue or other issue.
Thanks  for your support.
